=head1 PerlFu

A Centralized Perl Knowledgebase

Devin Austin

L<dhoss@cpan.org>

=head1 What is PerlFu?

=over 

=item A Perl knowledgebase that indexes information from reliable sources

=over 

=item *

blogs.perl.org

=item *

module docs (L<http://metacpan.org>)

=item *

Perlmonks

=item *

stackoverflow

=item *

user submitted data

=back

=back

=head1 What is PerlFu? (cont'd)

=over

=item *

Threaded forums

=over

=item *

Stackoverflow and Perlmonks already have this!

=over

=item *

Perlmonks == slow, bogged down, shitty search

=item * 

Stackoverflow is an alright thing.  It could be narrowed down to a much more focused scope.

=back

=back

=item *

Favorites

=back
