=head1 PerlFu

A Centralized Perl Knowledgebase

Devin Austin

L<dhoss@cpan.org>

=head1 What is PerlFu?


=item A Perl knowledgebase that indexes information from reliable sources

=over 

=item *

blogs.perl.org

=item *

module docs (L<http://metacpan.org>)

=item *

Perlmonks

=item *

stackoverflow

=item *

user submitted data


=back

=head1 What is PerlFu? (cont'd)


=item *

Threaded forums

=over

=item *

Stackoverflow and Perlmonks already have this!

=over

=item *

Perlmonks == slow, bogged down, shitty search

=item * 

Stackoverflow is an alright thing.  It could be narrowed down to a much more focused scope.

=back



=back

=head1 What is PerlFu? (cont'd)

=item *

Favorites

=over

=item * 

Bookmark your favorite documentation, code, code snippets, modules (using metacpan), documentation, and be able to search them


=item *

Useful because I personally can't sift throught my Chrome bookmarks efficiently

=back


=head1 What is PerlFu? (cont'd)

=item Recipes for:

=over

=item * 

Catalyst application deployment

=over

=item *

the advent of Plack has helped this a whole hell of a lot, but frankly I find the Catalyst Wiki a bit like trying to hit a fly with a brick. 

=item *

From across the room.

=item * 

Drunk. (no slight towards MojoMojo intended)


=back

=back

=head1 What is PerlFu? (cont'd)

=item Catalyst Advent Calendar

=over

=item *

Though retired, it still contains a whole lot of relevant and good information.

=item * 

DBIx::Class Intricacies

=over

=item *

This ORM is a beautiful thing, and I'm indebted for life to mst for creating something that allows me to not have to have the slightest clue what I'm doing in SQL and still get things done. However, the rabbit hole goes deep, and I want to add a map to the goodies.

=back

=back
